# GitHub Pages settings
source: bazel-bin/site
title: Bazel Rules Documentation
description: >- # this means to ignore newlines until "baseurl:"
  API Documentation for Bazel rules.
baseurl: "/doc.bzl" # the subpath of your site, e.g. /blog
url: "https://doc.bzl.dev" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
markdown: GFM
permalinks: pretty
plugins:
  - jekyll-feed
