# GitHub Pages settings
source: bazel-bin/site
title: Bazel Rules Documentation
description: >-
  API Documentation for Bazel rules.
url: "https://alexeagle.github.io"
baseurl: "/doc.bzl"

# Build settings
theme: minima
markdown: GFM
